### ISSUE TITLE
5.1 crashes with no data (new install)

### ISSUE THREAD

**Issue by goldfndr** [westnordost/StreetComplete#1048]
While trying to troubleshoot another issue (#975 not solved by #1024 as of versions 5.0 and 5.1; screenshot available upon request), I decided to clear data (after moving the /data/data/… directory so it wouldn't be found). 5.1 crashes with the following log (via CatLog using "street" filter; I can reproduce if something was missed by the filter).

```
05-04 01:55:40.362 I/ActivityManager( 1568): START u0 {act=android.intent.action.MAIN flg=0x10000000 cmp=de.westnordost.streetcomplete/.MainActivity bnds=[360,816][480,999]} from pid 19548
05-04 01:55:40.446 I/ActivityManager( 1568): Start proc de.westnordost.streetcomplete for activity de.westnordost.streetcomplete/.MainActivity: pid=16811 uid=10480 gids={50480, 3003}
05-04 01:55:40.614 W/ContextImpl(16811): Unable to create cache directory /data/data/de.westnordost.streetcomplete/cache
05-04 01:55:40.722 E/SQLiteLog(16811): (14) os_unix.c:30191: (2) open(/data/data/de.westnordost.streetcomplete/databases/streetcomplete.db) - 
05-04 01:55:40.731 E/SQLiteDatabase(16811): Failed to open database '/data/data/de.westnordost.streetcomplete/databases/streetcomplete.db'.
05-04 01:55:40.731 E/SQLiteDatabase(16811): 	at de.westnordost.streetcomplete.quests.localized_name.data.RoadNameSuggestionsDao.<init>(RoadNameSuggestionsDao.java:32)
05-04 01:55:40.731 E/SQLiteDatabase(16811): 	at de.westnordost.streetcomplete.quests.localized_name.data.RoadNameSuggestionsDao_Factory.get(RoadNameSuggestionsDao_Factory.java:26)
05-04 01:55:40.731 E/SQLiteDatabase(16811): 	at de.westnordost.streetcomplete.quests.localized_name.data.RoadNameSuggestionsDao_Factory.get(RoadNameSuggestionsDao_Factory.java:9)
05-04 01:55:40.731 E/SQLiteDatabase(16811): 	at de.westnordost.streetcomplete.quests.QuestModule_QuestTypeRegistryFactory.get(QuestModule_QuestTypeRegistryFactory.java:43)
05-04 01:55:40.731 E/SQLiteDatabase(16811): 	at de.westnordost.streetcomplete.quests.QuestModule_QuestTypeRegistryFactory.get(QuestModule_QuestTypeRegistryFactory.java:13)
05-04 01:55:40.731 E/SQLiteDatabase(16811): 	at de.westnordost.streetcomplete.DaggerApplicationComponent.getTangramQuestSpriteSheetCreator(DaggerApplicationComponent.java:229)
05-04 01:55:40.731 E/SQLiteDatabase(16811): 	at de.westnordost.streetcomplete.DaggerApplicationComponent.injectStreetCompleteApplication(DaggerApplicationComponent.java:583)
05-04 01:55:40.731 E/SQLiteDatabase(16811): 	at de.westnordost.streetcomplete.DaggerApplicationComponent.inject(DaggerApplicationComponent.java:491)
05-04 01:55:40.731 E/SQLiteDatabase(16811): 	at de.westnordost.streetcomplete.StreetCompleteApplication.onCreate(StreetCompleteApplication.java:34)
05-04 01:55:40.742 E/AndroidRuntime(16811): Process: de.westnordost.streetcomplete, PID: 16811
05-04 01:55:40.742 E/AndroidRuntime(16811): java.lang.RuntimeException: Unable to create application de.westnordost.streetcomplete.StreetCompleteApplication: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
05-04 01:55:40.742 E/AndroidRuntime(16811): 	at de.westnordost.streetcomplete.quests.localized_name.data.RoadNameSuggestionsDao.<init>(RoadNameSuggestionsDao.java:32)
05-04 01:55:40.742 E/AndroidRuntime(16811): 	at de.westnordost.streetcomplete.quests.localized_name.data.RoadNameSuggestionsDao_Factory.get(RoadNameSuggestionsDao_Factory.java:26)
05-04 01:55:40.742 E/AndroidRuntime(16811): 	at de.westnordost.streetcomplete.quests.localized_name.data.RoadNameSuggestionsDao_Factory.get(RoadNameSuggestionsDao_Factory.java:9)
05-04 01:55:40.742 E/AndroidRuntime(16811): 	at de.westnordost.streetcomplete.quests.QuestModule_QuestTypeRegistryFactory.get(QuestModule_QuestTypeRegistryFactory.java:43)
05-04 01:55:40.742 E/AndroidRuntime(16811): 	at de.westnordost.streetcomplete.quests.QuestModule_QuestTypeRegistryFactory.get(QuestModule_QuestTypeRegistryFactory.java:13)
05-04 01:55:40.742 E/AndroidRuntime(16811): 	at de.westnordost.streetcomplete.DaggerApplicationComponent.getTangramQuestSpriteSheetCreator(DaggerApplicationComponent.java:229)
05-04 01:55:40.742 E/AndroidRuntime(16811): 	at de.westnordost.streetcomplete.DaggerApplicationComponent.injectStreetCompleteApplication(DaggerApplicationComponent.java:583)
05-04 01:55:40.742 E/AndroidRuntime(16811): 	at de.westnordost.streetcomplete.DaggerApplicationComponent.inject(DaggerApplicationComponent.java:491)
05-04 01:55:40.742 E/AndroidRuntime(16811): 	at de.westnordost.streetcomplete.StreetCompleteApplication.onCreate(StreetCompleteApplication.java:34)
05-04 01:55:40.758 W/ActivityManager( 1568):   Force finishing activity de.westnordost.streetcomplete/.MainActivity
05-04 01:55:41.279 W/ActivityManager( 1568): Activity pause timeout for ActivityRecord{42576ae0 u0 de.westnordost.streetcomplete/.MainActivity t168 f}
05-04 01:55:42.564 D/SFPerfTracer(  362):        layers: (6:15) (DimLayer: 0:216) (DimLayer: 0:22)* (FocusedStackFrame: 0:1821)* (StatusBar: 1:298180) (NavigationBar: 0:15772) (com.android.systemui.ImageWallpaper: 0:2650) (Sprite: 0:57158)* (DimLayer: 0:2499)* (DimLayer: 0:291)* (Sprite: 0:96054)* (Sprite: 0:41159)* (net.pierrox.lightning_launcher_extreme/net.pierrox.lightning_launcher.activities.AppDrawerX: 0:270)* (Starting de.westnordost.streetcomplete: 0:51)* (Application Error: de.westnordost.streetcomplete: 16:36) (net.pierrox.lightning_launcher_extreme/net.pierrox.lightning_launcher.activities.Dashboard: 0:8) 
05-04 01:55:43.178 I/ActivityManager( 1568): Process de.westnordost.streetcomplete (pid 16811) has died.
05-04 01:55:48.301 D/SFPerfTracer(  362):        layers: (4:16) (DimLayer: 0:229)* (DimLayer: 0:22)* (FocusedStackFrame: 0:1825)* (StatusBar: 0:298184) (NavigationBar: 0:15782) (com.android.systemui.ImageWallpaper: 0:2650) (Sprite: 1:57201)* (DimLayer: 0:2499)* (DimLayer: 0:291)* (Sprite: 0:96054)* (Sprite: 0:41159)* (Starting de.westnordost.streetcomplete: 0:51)* (Application Error: de.westnordost.streetcomplete: 0:50)* (net.pierrox.lightning_launcher_extreme/net.pierrox.lightning_launcher.activities.Dashboard: 0:43)* (com.android.systemui/com.android.systemui.recent.RecentsActivity: 0:28) (com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity: 17:20)* 
```

I uninstalled 5.1 and installed 5.0 from the GitHub releases page. No crash with no data (although I did give a download error; email sent but not reproducible in 5.1). 5.1 *does* work if the partial data from 5.0 is present.

With the data downloaded by 5.1, I'm no longer getting speed limit quests (but was with 5.0).

**Comment by westnordost** [comment]
I think this might have happened because you first had the version signed by F-Droid and then the version signed by me. What if you install the 5.1 from F-Droid?

**Comment by rugk** [comment]
Actually it should not be possible to install the app like that then.

**Comment by westnordost** [comment]
Yeah, it shouldn't. I am really quite in the dark about this. The error is that it cannot open the database - no rights? I is this even possible?

**Comment by goldfndr** [comment]
What I've found is that by renaming the /data/data directory and trying to run the program, even if I delete the directory I renamed and the /data/app-lib directory, the app crashes, but If I then do an uninstall and new install, the app works fine. So I'm thinking it was a permissions issue of my own creation. So I'm closing this issue.
