### ISSUE TITLE
unmodified recent master crashes on add oneway quest 

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1096]
Tested with 6b6af984

I suspect that it may crash if no quests are found in a given scan but it is just a wild guess

```
Device: Xiaomi prada, Android 6.0.1
de.westnordost.osmapi.common.errors.OsmBadUserInputException: Bad Request
(400) - <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8"
lang="en"/>  
  <title>OSM3S Response</title>
</head>
<body>

<p>The data included in this document is from www.openstreetmap.org. The
data is made available under ODbL.</p>
<p><strong style="color:#FF0000">Error</strong>: line 1: static error: For
the attribute "ref" of the element "id-query" the only allowed values are
positive integers. </p>

</body>
</html>

at
de.westnordost.osmapi.OsmApiErrorFactory.createError(OsmApiErrorFactory.java:37)
at
de.westnordost.osmapi.OsmConnection.handleResponseCode(OsmConnection.java:343)
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:189)
at
de.westnordost.streetcomplete.data.osm.download.OverpassMapDataDao.get(OverpassMapDataDao.java:60)
at
de.westnordost.streetcomplete.data.osm.download.OverpassMapDataDao.getAndHandleQuota(OverpassMapDataDao.java:84)
at
de.westnordost.streetcomplete.quests.oneway.AddOneway.download(AddOneway.java:61)
at
de.westnordost.streetcomplete.data.osm.download.OsmQuestDownload.download(OsmQuestDownload.java:76)
at
de.westnordost.streetcomplete.data.download.QuestDownload.downloadQuestTypes(QuestDownload.java:200)
at
de.westnordost.streetcomplete.data.download.QuestDownload.download(QuestDownload.java:124)
at
de.westnordost.streetcomplete.data.download.QuestDownloadService$ServiceHandler.handleMessage(QuestDownloadService.java:185)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.os.HandlerThread.run(HandlerThread.java:61) P9
```

**Comment by westnordost** [comment]
Can you give the location where you scanned for quests?

**Comment by matkoniecz** [comment]
south of Kraków and Zakopane, both in Poland (if that is enough, ping me - I may give more exact location in the evening)
