### ISSUE TITLE
de.westnordost.streetcomplete.data.upload.QuestChangesUploadService called with no changes to upload

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1253]
I noticed it and reproduced it with blank fresh install (uninstall dev build, install from scratch).

From logcat:
```
11-05 13:39:50.780 2166-2267/de.westnordost.streetcomplete.debug E/QuestChangesUpload: Unable to upload changes
                                                                                       de.westnordost.osmapi.common.errors.OsmAuthorizationException: Unauthorized (401) - User is not authorized
                                                                                           at de.westnordost.streetcomplete.data.upload.QuestChangesUploadService.onHandleIntent(QuestChangesUploadService.java:108)
                                                                                           at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
```

Mobile network consumption by failed login is not big, but how often it is called despite that there are no change to upload?

It has additional undesirable effect that before user has chance to solve even single quest he/she gets screen that something went wrong and requests a registration.

That is especially unfriendly for people who have not (yet) an OSM user account.

**Comment by westnordost** [comment]
Thanks for the report!
