### ISSUE TITLE
Out of memory error when trying to display too many quests

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#137]
```
java.lang.OutOfMemoryError: Failed to allocate a 202481348 byte allocation with 6668266 free bytes and 182MB until OOM
	at java.util.ArrayList.<init>(ArrayList.java:151)
	at de.westnordost.streetcomplete.util.SlippyMapMath.asTileList(SlippyMapMath.java:71)
	at de.westnordost.streetcomplete.tangram.QuestsMapFragment.updateView(QuestsMapFragment.java:196)
	at de.westnordost.streetcomplete.tangram.MapFragment.onPan(MapFragment.java:262)
	at com.mapzen.tangram.MapController$5.onPan(MapController.java:615)
	at com.mapzen.tangram.TouchInput.onDown(TouchInput.java:386)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:590)
	at com.mapzen.tangram.TouchInput.onTouch(TouchInput.java:333)
	at android.view.View.dispatchTouchEvent(View.java:10020)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:414)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3064)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:376)
	at android.view.View.dispatchPointerEvent(View.java:10244)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4444)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4312)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4005)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4062)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6253)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6227)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6188)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6356)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:6128)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

The app tries to display the already downloaded quests in an area of about 3000x3000 fields (the are is usually limited to 2x2 fields. This leads to a memory overflow. To calculate the size of this field, the app relies on info it gets from tangram-es: Getting current zoom level, getting current GPS position by screen coordinates.

**Comment by westnordost** [comment]
Aha, got some crash reports now:

java.lang.RuntimeException: Tried to display quests in a rectangle of 5x8 tiles, current zoom is 14.183409. Currently displayed area by screen borders is minlat=38.8520727, minlon=-77.4423176, maxlat=38.9877977, maxlon=-77.3334764
	at de.westnordost.streetcomplete.tangram.QuestsMapFragment.updateView(QuestsMapFragment.java:204)
	at de.westnordost.streetcomplete.tangram.MapFragment.followPosition(MapFragment.java:235)
	at de.westnordost.streetcomplete.tangram.MapFragment.initMap(MapFragment.java:139)
	at de.westnordost.streetcomplete.tangram.QuestsMapFragment.initMap(QuestsMapFragment.java:83)
	at de.westnordost.streetcomplete.tangram.MapFragment$1.onMapReady(MapFragment.java:103)
	at com.mapzen.tangram.MapView$1.onPostExecute(MapView.java:94)
	at com.mapzen.tangram.MapView$1.onPostExecute(MapView.java:79)
	at android.os.AsyncTask.finish(AsyncTask.java:667)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
