### ISSUE TITLE
Bad Request (400) - Version may not be negative at line 1 

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#1408]
I received some error reports with this stack trace today:

```
        de.westnordost.osmapi.common.errors.OsmBadUserInputException: Bad Request (400) - Version may not be negative at line 1, column 148
        at de.westnordost.osmapi.OsmApiErrorFactory.createError(OsmApiErrorFactory.java:37)
        at de.westnordost.osmapi.OsmConnection.handleResponseCode(OsmConnection.java:349)
        at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:195)
        at de.westnordost.osmapi.OsmConnection.makeAuthenticatedRequest(OsmConnection.java:161)
        at de.westnordost.osmapi.map.MapDataDao.uploadChanges(MapDataDao.java:120)
        at de.westnordost.streetcomplete.data.osm.upload.OsmQuestChangeUpload.uploadQuestChange(OsmQuestChangeUpload.java:123)
        at de.westnordost.streetcomplete.data.osm.upload.OsmQuestChangeUpload.upload(OsmQuestChangeUpload.java:97)
        at de.westnordost.streetcomplete.data.osm.upload.AOsmQuestChangesetsUpload.uploadAndHandleChangesetConflict(AOsmQuestChangesetsUpload.java:166)
        at de.westnordost.streetcomplete.data.osm.upload.AOsmQuestChangesetsUpload.upload(AOsmQuestChangesetsUpload.java:107)
        at de.westnordost.streetcomplete.data.upload.QuestChangesUploadService.onHandleIntent(QuestChangesUploadService.java:129)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by OliverParoczai** [comment]
Thanks for the fix! Appreciate it. :)
