### ISSUE TITLE
Trouble finding quests

### ISSUE THREAD

**Issue by kuba-orlik** [westnordost/StreetComplete#1497]
I've recently visited Gdynia (Poland) and had some time to spare while waiting for a train. I wanted to do some mapping, but SC showed few quests, and they were beyond my reach:

![photo_2019-07-26_19-42-28](https://user-images.githubusercontent.com/2697916/61970820-d7859580-afdd-11e9-8814-a61b17e74bbe.jpg)

I've tried disabling the "What is the name of this road" quest type, to trigger download of other quests that would be nearer to me, but failed to do so. 

I remember I had a similar situation in Elbląg, Poland - but there I was able to survey the nameless roads and solve the quests, and after that other quests appeard. 

It seems that:

* road name tags have high priority and make other quests not show up, and this affects quests in the whole city/district? Or at least the effect has a very long range
* disabling a quest type with high priority does not make quests with lower priority show up on the map

I might be wrong, but my recent issues with quest downloading seems to support the above assupmtions

**Comment by matkoniecz** [comment]
Thanks for reporting!

> I've tried disabling the "What is the name of this road" quest type, to trigger download of other quests that would be nearer to me, but failed to do so.

I replicated this part - disabling all visible quests is not resulting in downloading more.

For now workaround is to trigger manual download ("scan for quests here", "Szukaj tutaj zadań" in the Polish version).

**Comment by kuba-orlik** [comment]
I've tried downloading right now and it toasted an error, inspecting with logcat shows 

```
Unable to download quests
de.westnordost.osmapi.common.errors.OsmConnectionException: java.net.SocketTimeoutException: timeout
 at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:202)
 at de.westnordost.streetcomplete.data.osm.download.OverpassMapDataDao.get(OverpassMapDataDao.java:60)
 at de.westnordost.streetcomplete.data.osm.download.OverpassMapDataDao.getAndHandleQuota(OverpassMapDataDao.java:84)
 at de.westnordost.streetcomplete.quests.place_name.AddPlaceName.download(AddPlaceName.kt:64)
 at de.westnordost.streetcomplete.data.osm.download.OsmQuestDownload.download(OsmQuestDownload.java:90)
 at de.westnordost.streetcomplete.data.download.QuestDownload.downloadQuestTypes(QuestDownload.java:200)
 at de.westnordost.streetcomplete.data.download.QuestDownload.download(QuestDownload.java:124)
 at de.westnordost.streetcomplete.data.download.QuestDownloadService$ServiceHandler.handleMessage(QuestDownloadService.java:207)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:164)
 at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: java.net.SocketTimeoutException: timeout
 at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
 at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
 at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
 at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
 at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
 at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
 at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
 at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
 at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
 at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
 at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
 at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(Unknown Source:0)
 at de.westnordost.osmapi.OsmConnection.handleResponseCode(OsmConnection.java:341)
 at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:195)
 ... 10 more
Caused by: java.net.SocketException: socket is closed
 at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
 at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
 at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
 ... 24 more
```

**Comment by matkoniecz** [comment]
> java.net.SocketTimeoutException: timeout

This is a separate issue (fixed by https://github.com/westnordost/StreetComplete/pull/1472 - not yet in the released version)

**Comment by westnordost** [comment]
> For some reason ... results in return, even with no visible quests at all as long as there is plenty of hidden ones.

Oh, right, `osmQuestDB.getCount(bbox, QuestStatus.NEW);` returns all new unanswered quests. Also quests of quest types that have been disabled.

**Comment by Mannshoch** [comment]
I'm not sure if it was this fix. But after updating this app. I now have many many more quest's to answer. 
Thanks!
