### ISSUE TITLE
in interface debug it is impossible to inspect road name view

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1643]
Display crashes with `de.westnordost.streetcomplete.data.osm.ElementPointGeometry cannot be cast to de.westnordost.streetcomplete.data.osm.ElementPolylinesGeometry`

```
    java.lang.ClassCastException: de.westnordost.streetcomplete.data.osm.ElementPointGeometry cannot be cast to de.westnordost.streetcomplete.data.osm.ElementPolylinesGeometry
        at de.westnordost.streetcomplete.quests.localized_name.AddRoadNameForm.getRoadNameSuggestions(AddRoadNameForm.kt:43)
        at de.westnordost.streetcomplete.quests.localized_name.AddRoadNameForm.setupNameAdapter(AddRoadNameForm.kt:38)
        at de.westnordost.streetcomplete.quests.localized_name.AAddLocalizedNameForm.initLocalizedNameAdapter(AAddLocalizedNameForm.kt:52)
        at de.westnordost.streetcomplete.quests.localized_name.AAddLocalizedNameForm.onViewCreated(AAddLocalizedNameForm.kt:42)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5441)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

**Comment by matkoniecz** [comment]
My initial though is to modify `getRoadNameSuggestions()` to handle both ways and points.

**Comment by matkoniecz** [comment]
Similar issues happen in cycleway quest, sidewalk and oneway quest, as this quests expect element (that modifies interface).

Maybe it would be better to show quest form instantiate way geometry and pass it to affected quests.

Quests may self declare as requiring way geometry with new function `override fun typicalGeometry()` that would return point by default but could be overriden to ways and areas, this would be respected at https://github.com/westnordost/StreetComplete/blob/462bb59301a9c0059d4cc012d1c9acfc2917b6e1/app/src/main/java/de/westnordost/streetcomplete/settings/ShowQuestFormsActivity.kt#L83 .

**Comment by matkoniecz** [comment]
And I found more reasonable way to do this.
