### ISSUE TITLE
[Bug] Crash on 17.0 beta

### ISSUE THREAD

**Issue by Atrate** [westnordost/StreetComplete#1704]
```
time: 1580156362071
msg: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
stacktrace: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at android.app.SharedPreferencesImpl.getLong(SharedPreferencesImpl.java:315)
	at de.westnordost.streetcomplete.map.MapFragment.createHttpHandler(MapFragment.kt:169)
	at de.westnordost.streetcomplete.map.MapFragment.initMap(MapFragment.kt:108)
	at de.westnordost.streetcomplete.map.MapFragment$onViewCreated$1.invokeSuspend(MapFragment.kt:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)

```
Android 10, rooted

**Comment by Atrate** [comment]
Fixed in 72e865b?

**Comment by westnordost** [comment]
Not yet, but now! Thanks for the report!

**Comment by HolgerJeromin** [comment]
Are these 17.x releases on play store?
I am an beta tester there an still on v16.1

Motorola g7 Power with android 9

**Comment by westnordost** [comment]
I rolled it out to only 20%. Because 80% of StreetComplete users are beta testers, rolling out betas to 100% would be almost like a public release. When there are no more critical bugs, I will put it on 100%.

**Comment by peternewman** [comment]
I assume this is the same crash I was seeing. I commented on the Play beta as I wasn't logged into GitHub at the time. Have you released beta 2 and will it get pushed to the people who currently have beta 1 given that's currently broken?

**Comment by westnordost** [comment]
Yes and yes

**Comment by HolgerJeromin** [comment]
> Because 80% of StreetComplete users are beta testers

Impressive rate :-)

**Comment by peternewman** [comment]
> Yes and yes

Thanks beta 2 is loading for me now thanks.
