### ISSUE TITLE
Crash at app start

### ISSUE THREAD

**Issue by hontogit** [westnordost/StreetComplete#2006]
I just updated SC from version 21.2 to 22.0 from f-droid.
When I open the app it immediately crashes.
This is what I got as information with logcat

```
[08-10 12:39:11.114 7539:7582 E/AndroidRuntime]
FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: de.westnordost.streetcomplete, PID: 7539
java.lang.IllegalAccessError: Field 'org.apache.commons.codec.binary.Base64.lookUpBase64Alphabet' is inaccessible to class 'oauth.signpost.signature.HmacSha1MessageSigner' (declaration of 'oauth.signpost.signature.HmacSha1MessageSigner' appears in /data/app/de.westnordost.streetcomplete-1/base.apk)
	at oauth.signpost.signature.HmacSha1MessageSigner.base64Encode(HmacSha1MessageSigner.java:9)
	at oauth.signpost.signature.HmacSha1MessageSigner.sign(HmacSha1MessageSigner.java:13)
	at oauth.signpost.basic.DefaultOAuthConsumer.sign(DefaultOAuthConsumer.java:22)
	at de.westnordost.osmapi.OsmConnection.sendRequest(OsmConnection.java:22)
	at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:2)
	at de.westnordost.osmapi.OsmConnection.makeAuthenticatedRequest(OsmConnection.java:1)
	at de.westnordost.streetcomplete.data.user.UserController$updateUser$1.invokeSuspend(UserController.kt:5)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

[08-10 12:39:11.117 1825:2312 W/ActivityManager]
  Force finishing activity de.westnordost.streetcomplete/.MainActivity
```

**How to Reproduce**
Start the App

**Versions affected**
Android 7.1.2
StreetComplete 22.0

**Comment by Hawaiihemd** [comment]
I second that. Same exception here.

**Comment by westnordost** [comment]
Yes, I am getting a lot of crash reports since yesterday or so. Something must have changed in ... I don't know ... I did not update any dependencies I know of, maybe the Android platform?? Anyway, it looks like the OAuth signpost library issued an update that seems to workaround this issue so I just need to update osmapi to the new major version:

https://github.com/mttkay/signpost/releases
