### ISSUE TITLE
Crash after upgrade to 22.0

### ISSUE THREAD

**Issue by JulienPalard** [westnordost/StreetComplete#2011]
**How to Reproduce**
Try to open the app, crash.

**Versions affected**

22.0, on Nexus 6P (Angler) running LineageOS 15.1.

```
08-11 19:45:37.962  5581  5613 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
08-11 19:45:37.962  5581  5613 E AndroidRuntime: Process: de.westnordost.streetcomplete, PID: 5581
08-11 19:45:37.962  5581  5613 E AndroidRuntime: java.lang.IllegalAccessError: Field 'org.apache.commons.codec.binary.Base64.lookUpBase64Alphabet' is inaccessible to class 'oauth.signpost.signature.HmacSha1MessageSigner' (declaration of 'oauth.signpost.signature.HmacSha1MessageSigner' appears in /data/app/de.westnordost.streetcomplete-x1Ib5ady9RYfRGAML8Jzpw==/base.apk)
08-11 19:45:37.962  5581  5613 E AndroidRuntime: 	at oauth.signpost.signature.HmacSha1MessageSigner.base64Encode(HmacSha1MessageSigner.java:9)
08-11 19:45:37.962  5581  5613 E AndroidRuntime: 	at oauth.signpost.signature.HmacSha1MessageSigner.sign(HmacSha1MessageSigner.java:13)
08-11 19:45:37.962  5581  5613 E AndroidRuntime: 	at oauth.signpost.basic.DefaultOAuthConsumer.sign(DefaultOAuthConsumer.java:22)
08-11 19:45:37.962  5581  5613 E AndroidRuntime: 	at de.westnordost.osmapi.OsmConnection.sendRequest(OsmConnection.java:22)
08-11 19:45:37.962  5581  5613 E AndroidRuntime: 	at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:2)
08-11 19:45:37.962  5581  5613 E AndroidRuntime: 	at de.westnordost.osmapi.OsmConnection.makeAuthenticatedRequest(OsmConnection.java:1)
08-11 19:45:37.962  5581  5613 E AndroidRuntime: 	at de.westnordost.streetcomplete.data.user.UserController$updateUser$1.invokeSuspend(UserController.kt:5)
08-11 19:45:37.962  5581  5613 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
08-11 19:45:37.962  5581  5613 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
08-11 19:45:37.962  5581  5613 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
08-11 19:45:37.962  5581  5613 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

```

While I'm here: I enjoy this app a lot, thanks for the work, thanks for making it envolve continuously, as a user it's really appreciated.

**Comment by matkoniecz** [comment]
sounds like #2006 with fix implemented but not released yet ( see https://github.com/westnordost/StreetComplete/releases )

**Comment by JulienPalard** [comment]
Duplicate of https://github.com/westnordost/StreetComplete/issues/2006.

Should have looked at closed issues too. Went too fast.

**Comment by smichel17** [comment]
It might be a good idea to leave this or #2006 open until the fix is released, to make it easier for others to find it.

**Comment by westnordost** [comment]
> sounds like #2006 with fix implemented but not released yet ( see https://github.com/westnordost/StreetComplete/releases )

Why, it is released, look: https://github.com/westnordost/StreetComplete/releases/tag/v22.1

**Comment by matkoniecz** [comment]
Sorry, it probably hides in "and more" part.

**Comment by westnordost** [comment]
Ha, actually I mistakenly mentioned #2007 but I meant to mention #2006.
