### ISSUE TITLE
Crash when pressing login button on Shift OS L

### ISSUE THREAD

**Issue by ChristophHaag** [westnordost/StreetComplete#2015]
Shift OS L is a custom Android 8.0 (soon 8.1) build without google apps for Shift Phones from the vendor itself.

```
08-12 19:05:01.493 18794 18794 E AndroidRuntime: FATAL EXCEPTION: main
08-12 19:05:01.493 18794 18794 E AndroidRuntime: Process: de.westnordost.streetcomplete, PID: 18794
08-12 19:05:01.493 18794 18794 E AndroidRuntime: java.lang.IllegalAccessError: Field 'org.apache.commons.codec.binary.Base64.lookUpBase64Alphabet' is inaccessible to class 'oauth.signpost.signature.HmacSha1MessageSigner' (declaration of 'oauth.signpost.signature.HmacSha1MessageSigner' appears in base.apk)
08-12 19:05:01.493 18794 18794 E AndroidRuntime:        at oauth.signpost.signature.HmacSha1MessageSigner.base64Encode(HmacSha1MessageSigner.java:9)
08-12 19:05:01.493 18794 18794 E AndroidRuntime:        at oauth.signpost.signature.HmacSha1MessageSigner.sign(HmacSha1MessageSigner.java:13)
08-12 19:05:01.493 18794 18794 E AndroidRuntime:        at oauth.signpost.basic.DefaultOAuthConsumer.sign(DefaultOAuthConsumer.java:22)
08-12 19:05:01.493 18794 18794 E AndroidRuntime:        at oauth.signpost.basic.DefaultOAuthProvider.retrieveToken(DefaultOAuthProvider.java:9)
08-12 19:05:01.493 18794 18794 E AndroidRuntime:        at oauth.signpost.basic.DefaultOAuthProvider.retrieveRequestToken(DefaultOAuthProvider.java:6)
08-12 19:05:01.493 18794 18794 E AndroidRuntime:        at de.westnordost.streetcomplete.settings.OAuthFragment$continueAuthentication$2.invokeSuspend(OAuthFragment.kt:6)
08-12 19:05:01.493 18794 18794 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
08-12 19:05:01.493 18794 18794 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
08-12 19:05:01.493 18794 18794 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
08-12 19:05:01.493 18794 18794 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
08-12 19:05:01.499  1093 18791 W ActivityManager:   Force finishing activity de.westnordost.streetcomplete/.user.UserActivity
```

**Comment by westnordost** [comment]
Nice, a shift phone user, congrats! Anyway, this is already fixed, see #2006
