### ISSUE TITLE
Connection error while trying to scan for quests

### ISSUE THREAD

**Issue by Scafir** [westnordost/StreetComplete#2048]
Searching for quests fails when quest type "What is the name of this place?" is enabled. 
This is particularly bad because it usually blocks any other type of quests from being displayed.

Here is the most interesting message log:
```
Unable to download quests
de.westnordost.osmapi.common.errors.OsmApiReadResponseException: de.westnordost.osmapi.common.errors.XmlParserException: Error parsing XML at END_TAG </node>@10:10 in java.io.InputStreamReader@2934c66
 at de.westnordost.osmapi.OsmConnection.handleResponse(OsmConnection.java:4)
 at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:4)
 at de.westnordost.osmapi.overpass.OverpassMapDataDao.queryElementsWithGeometry(OverpassMapDataDao.java:4)
 at de.westnordost.streetcomplete.data.osm.mapdata.OverpassMapDataAndGeometryApi.query(OverpassMapDataAndGeometryApi.kt:2)
 at de.westnordost.streetcomplete.quests.place_name.AddPlaceName.download(AddPlaceName.kt:6)
 at de.westnordost.streetcomplete.data.download.QuestDownloader.downloadQuestType(QuestDownloader.kt:33)
 at de.westnordost.streetcomplete.data.download.QuestDownloader.download(QuestDownloader.kt:17)
 at de.westnordost.streetcomplete.data.download.SingleIntentService$ServiceHandler.handleMessage(SingleIntentService.kt:17)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:214)
 at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: de.westnordost.osmapi.common.errors.XmlParserException: Error parsing XML at END_TAG </node>@10:10 in java.io.InputStreamReader@2934c66
 at de.westnordost.osmapi.common.XmlParser.doParse(XmlParser.java:15)
 at de.westnordost.osmapi.overpass.MapDataWithGeometryParser.parse(MapDataWithGeometryParser.java:3)
 at de.westnordost.osmapi.OsmConnection.handleResponse(OsmConnection.java:2)
 ... 10 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: No field map of type Ljava/util/Map; in class Lorg/json/JSONObject; or its superclasses (declaration of 'org.json.JSONObject' appears in /apex/com.android.runtime/javalib/core-libart.jar)
 at java.util.concurrent.FutureTask.report(FutureTask.java:123)
 at java.util.concurrent.FutureTask.get(FutureTask.java:193)
 at de.westnordost.streetcomplete.quests.place_name.AddPlaceName.hasFeatureName(AddPlaceName.kt:1)
 at de.westnordost.streetcomplete.quests.place_name.AddPlaceName$download$1.invoke(AddPlaceName.kt:3)
 at de.westnordost.streetcomplete.quests.place_name.AddPlaceName$download$1.invoke(AddPlaceName.kt:1)
 at de.westnordost.streetcomplete.data.osm.mapdata.OverpassMapDataAndGeometryApi$query$handler$1.handle(OverpassMapDataAndGeometryApi.kt:3)
 at de.westnordost.osmapi.overpass.MapDataWithGeometryParser.onEndElement(MapDataWithGeometryParser.java:34)
 at de.westnordost.osmapi.common.XmlParser.doParse(XmlParser.java:8)
 ... 12 more
Caused by: java.lang.NoSuchFieldError: No field map of type Ljava/util/Map; in class Lorg/json/JSONObject; or its superclasses (declaration of 'org.json.JSONObject' appears in /apex/com.android.runtime/javalib/core-libart.jar)
 at de.westnordost.osmfeatures.iDFeatureCollection.parseStringMap(iDFeatureCollection.java:3)
 at de.westnordost.osmfeatures.iDFeatureCollection.parseFeatures(iDFeatureCollection.java:6)
 at de.westnordost.osmfeatures.iDFeatureCollection.<init>(iDFeatureCollection.java:4)
 at de.westnordost.streetcomplete.data.meta.MetadataModule$featureDictionaryFuture$1.call(MetadataModule.kt:2)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at de.westnordost.streetcomplete.StreetCompleteApplication.lambda$preload$1$StreetCompleteApplication(StreetCompleteApplication.java:1)
 at de.westnordost.streetcomplete.-$$Lambda$StreetCompleteApplication$TOPCfQEhitCcMdF2wUE8N5y0WBQ.run(Unknown Source:2)
 at java.lang.Thread.run(Thread.java:919)
```

**How to Reproduce**
1) Install the app
2) Log in
3) Search for quests

**Versions affected**
Android 10 (LineageOS 17.1 + MicroG)
StreetComplete 22.2

**Comment by matkoniecz** [comment]
Sounds like #2042 (F-droid release is controlled by third party, once they build and release 22.3 it should be fixed)

**Comment by Scafir** [comment]
Damn, sorry, I should have also searched for closed issues... 
Thank you for the info!
