### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by herver1971** [westnordost/StreetComplete#2084]
Xiaomi Mi9 Android 10

The application closes in version 23 beta when wanting to mark a sidewalk

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at android.graphics.Paint.getTextBounds(Paint.java:2796)
	at de.westnordost.streetcomplete.view.VerticalLabelView.onMeasure(VerticalLabelView.kt:58)
	at android.view.View.measure(View.java:24943)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:24943)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:24943)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24943)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:24943)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24943)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24943)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24943)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24943)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24943)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24943)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1599)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:585)
	at android.view.View.measure(View.java:24943)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24943)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
	at android.view.View.measure(View.java:24943)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:24943)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24943)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:24943)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:24943)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
	at android.view.View.measure(View.java:24943)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24943)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24943)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:24943)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:774)
	at android.view.View.measure(View.java:24943)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3099)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1913)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2207)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1801)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7795)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7560)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by Carnildo** [comment]
I get a crash with a similar stack trace when clicking on a "Does this have sidewalks" icon with Android 6 on a Nexus 7, so it's not something version- or model-specific.
