### ISSUE TITLE
Error if Contributor Terms not agreed to.

### ISSUE THREAD

**Issue by PriceChild** [westnordost/StreetComplete#210]
I have an old osm account I just used to log into StreetComplete.

I made a few edits but syncs failed with an error.

```
Device: google bullhead, Android 7.1.2
de.westnordost.osmapi.common.errors.OsmAuthorizationException: Forbidden (403) - You must accept the contributor terms before you can edit.
at de.westnordost.osmapi.OsmApiErrorFactory.createError(OsmApiErrorFactory.java:33)
at de.westnordost.osmapi.OsmConnection.handleResponseCode(OsmConnection.java:339)
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:189)
at de.westnordost.osmapi.OsmConnection.makeAuthenticatedRequest(OsmConnection.java:155)
at de.westnordost.osmapi.map.MapDataDao.openChangeset(MapDataDao.java:127)
at de.westnordost.streetcomplete.data.osm.upload.OsmQuestChangesUpload.createChangeset(OsmQuestChangesUpload.java:154)
at de.westnordost.streetcomplete.data.osm.upload.OsmQuestChangesUpload.getChangesetIdOrCreate(OsmQuestChangesUpload.java:144)
at de.westnordost.streetcomplete.data.osm.upload.OsmQuestChangesUpload.upload(OsmQuestChangesUpload.java:81)
at de.westnordost.streetcomplete.data.QuestChangesUploadService.onHandleIntent(QuestChangesUploadService.java:102)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)
```

On a hunch, I visited my openstreetmap.org profile and realised I hadn't agreed to the new (very old by now!) terms.

After agreeing, the app synced immediately.

It'd be nice if the app handled this failure and gave a hint.

**Comment by westnordost** [comment]
Too bad that you agreed already, now we can not reproduce it anymore.

Which version of StreetComplete are you using? Because I think this has been fixed since version 0.9 already.

**Comment by PriceChild** [comment]
Sorry about that. I haven't created a new account on openstreetmap.org but I'm guessing it's impossible without agreeing to the terms now?

I'm on 0.8 from F-Droid.
