### ISSUE TITLE
Error while uploading

### ISSUE THREAD

**Issue by Norwi** [westnordost/StreetComplete#2218]
After pressing the upload button I received an error message (in my case in German):
"Fehler beim Hochladen der Antworten". After pressing "Abbrechen", it seems to upload the last answer anyways.
(Additionally, my device is set to the correct date and time)

java.text.ParseException: Unparseable date: "2020-10-29 21:47:05 CET"
at java.text.DateFormat.parse(DateFormat.java:362)
at de.westnordost.streetcomplete.data.user.UserStore.getLastStatisticsUpdate(UserStore.kt:42)
at de.westnordost.streetcomplete.data.user.StatisticsUpdater.updateDaysActive(StatisticsUpdater.kt:49)
at de.westnordost.streetcomplete.data.user.StatisticsUpdater.addOne(StatisticsUpdater.kt:24)
at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestsUploader.onUploadSuccessful(OsmQuestsUploader.kt:35)
at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestsUploader.onUploadSuccessful(OsmQuestsUploader.kt:14)
at de.westnordost.streetcomplete.data.osm.upload.OsmInChangesetsUploader.upload(OsmInChangesetsUploader.kt:37)
at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestsUploader.upload(OsmQuestsUploader.kt:24)
at de.westnordost.streetcomplete.data.upload.UploadService.onHandleIntent(UploadService.kt:90)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.os.HandlerThread.run(HandlerThread.java:67)

**How to Reproduce**
Solve quests (in my case building type) and press upload.

**Versions affected**
Android 10
Streetcomplete v26.0-beta1

**Comment by westnordost** [comment]
Yes correct, upload is finished successfully, then after that the error occurs

**Comment by westnordost** [comment]
Sounds like there will be a bugfix release tomorrow 😬 

Thank you for testing, and make sure to test much more today so that I can add enhancements and bugfixes directly to the bugfix update 😄
