### ISSUE TITLE
java.text.ParseException: Unparseable date: "2020-10-27 22:09:13 CET"

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#2219]
V26.0 beta1
Uploading building type failed.

java.text.ParseException: Unparseable date: "2020-10-27 22:09:13 CET"
	at java.text.DateFormat.parse(DateFormat.java:362)
	at de.westnordost.streetcomplete.data.user.UserStore.getLastStatisticsUpdate(UserStore.kt:42)
	at de.westnordost.streetcomplete.data.user.StatisticsUpdater.updateDaysActive(StatisticsUpdater.kt:49)
	at de.westnordost.streetcomplete.data.user.StatisticsUpdater.addOne(StatisticsUpdater.kt:24)
	at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestsUploader.onUploadSuccessful(OsmQuestsUploader.kt:35)
	at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestsUploader.onUploadSuccessful(OsmQuestsUploader.kt:14)
	at de.westnordost.streetcomplete.data.osm.upload.OsmInChangesetsUploader.upload(OsmInChangesetsUploader.kt:37)
	at de.westnordost.streetcomplete.data.osm.osmquest.OsmQuestsUploader.upload(OsmQuestsUploader.kt:24)
	at de.westnordost.streetcomplete.data.upload.UploadService.onHandleIntent(UploadService.kt:90)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:241)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by matkoniecz** [comment]
#2218 fixed in https://github.com/westnordost/StreetComplete/commit/c38c3353cd6406993d28a35d8977f0133f44c590

**Comment by HolgerJeromin** [comment]
Damn. I looked for issues but only open ones. :-)

**Comment by matkoniecz** [comment]
@westnordost was really quick here :)

**Comment by smichel17** [comment]
It's also kind of GitHub's fault. The UI makes it really easy to forget to search closed issues.

**Comment by matkoniecz** [comment]
I have https://github.com/westnordost/StreetComplete/issues?utf8=%E2%9C%93&q=sort%3Aupdated-desc+ in bookmarks (all recently updated, including PRs and closed issues)
