### ISSUE TITLE
26.0-beta2 crashes immediately on start

### ISSUE THREAD

**Issue by kmpoppe** [westnordost/StreetComplete#2224]
... unfortunately without any call stack so I cannot provide any insightful stuff.

Samsung M31, installed from APK that's in the release assets.

Kai

**Comment by rouelibre1** [comment]
Same issue on my side (Samsung Galaxy A5 / Android 8.0.0)

**Comment by Harvester57** [comment]
Same here (Pocophone F1, Android 10)

**Comment by Esternouno** [comment]
Same probkem on Samsung S8+, Android 9

**Comment by Lotus815** [comment]
Same for me: Motorola Moto G5 / Android 8.1.0

**Comment by westnordost** [comment]
To get a stack trace would be really helpful, as I wasn't able to reproduce this so far. 
What if you delete the data, ist this still reproducible then?

**Comment by KenAlin** [comment]
Same here, on Pixel 4a running Android 11. Here are some screenshots about the error. App data were deleted before start. 

![Screenshot_20201101-195101_1](https://user-images.githubusercontent.com/12164749/97811629-29ef4080-1c7c-11eb-9d41-5c720aff426f.png)

![Screenshot_20201101-195134_1](https://user-images.githubusercontent.com/12164749/97811634-32e01200-1c7c-11eb-8e69-6b88cd11a270.png)

**Comment by westnordost** [comment]
I found there have been 62 crashes today with v26.0-beta2 in the google play console:

Problem: There is not even one line from streetcomplete here. Apparently the android system wants to display something, but where?

```
java.lang.IllegalAccessError: 
  at androidx.appcompat.widget.ContentFrameLayout.onAttachedToWindow (ContentFrameLayout.java:211)
  at android.view.View.dispatchAttachedToWindow (View.java:20479)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3489)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3496)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3496)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3496)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3496)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2411)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1946)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:8156)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:972)
  at android.view.Choreographer.doCallbacks (Choreographer.java:796)
  at android.view.Choreographer.doFrame (Choreographer.java:731)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:957)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:7656)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:592)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:947)
```

**Comment by westnordost** [comment]
@KenAlin Thanks Kevin, so that's the one.

Could someone downgrade to v26.0-beta1 to confirm that the problem does not exist for that version? I am really puzzled because a changed very little between v26.0-beta1 and beta2

**Comment by westnordost** [comment]
Ok, I can reproduce it, but only with the built and signed APK. When I deploy it directly from Android Studio, I can't

**Comment by Harvester57** [comment]
I uninstalled the beta2, and reinstalled beta1, works fine here.

**Comment by westnordost** [comment]
Maybe some build problem? I am going to prepare another beta release and post the candidate here, let's see if the problem persists for beta3 without having changed anything really.

**Comment by westnordost** [comment]
https://www.westnordost.de/misc/StreetComplete-v26.0-beta3.apk

Will test it myself first

**Comment by Harvester57** [comment]
Dirty installed it over beta2, still not working. Will try a clean install.

**Comment by westnordost** [comment]
Ok, the link I provided has hte same problem as beta2

**Comment by Lotus815** [comment]
Same for me, beta3 still crashing like beta2

**Comment by westnordost** [comment]
I'll rebuilt the beta1 and see if the problem persists, then inch my way forward each commit.

Apparently it is only reproducible with release versions even though there should be no difference between them (other than the debug version is debuggable)

**Comment by westnordost** [comment]
Haha lol, a rebuilt beta1 crashes just the same. What the fuck

**Comment by smichel17** [comment]
Maybe something in the environment changed?

**Comment by westnordost** [comment]
Well I did not update any dependencies

**Comment by smichel17** [comment]
@westnordost I assume you've already done a clean rebuild, but can you try wiping anything else that might be cached?

[`java.lang.IllegalAccessError`](https://docs.oracle.com/javase/7/docs/api/java/lang/IllegalAccessError.html) says,

> Normally, this error is caught by the compiler; this error can only occur at run time if the definition of a class has incompatibly changed.

And then when I look at the [ContentFrameLayout source](https://android.googlesource.com/platform/frameworks/support/+/a9ac247af2afd4115c3eb6d16c05bc92737d6305/v7/appcompat/src/main/java/androidx/appcompat/widget/ContentFrameLayout.java), we find that there is not actually anything on line 211, and no [changes to that file](https://android.googlesource.com/platform/frameworks/support/+log/a9ac247af2afd4115c3eb6d16c05bc92737d6305/v7/appcompat/src/main/java/androidx/appcompat/widget/ContentFrameLayout.java) in almost 3 years.

So, it seems likely to me that some local file was corrupted without the build system realizing it, and re-downloading it would fix the issue.

**Comment by Identitaet** [comment]
I have the error from the app in text form
Easier than looking at a screenshot

```
java.lang.IllegalAccessError: Illegal class access: 'androidx.appcompat.widget.ContentFrameLayout' attempting to access 'androidx.appcompat.app.AppCompatDelegateImpl$5' (declaration of 'androidx.appcompat.widget.ContentFrameLayout' appears in base.apk)
	at androidx.appcompat.widget.ContentFrameLayout.onAttachedToWindow(ContentFrameLayout.java:3)
	at android.view.View.dispatchAttachedToWindow(View.java:19665)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3458)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3465)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3465)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3465)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3465)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2128)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1819)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7781)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by westnordost** [comment]
So the classes.dex of the newly built beta1 is almost 1MB smaller than from the "real" beta1

**Comment by smichel17** [comment]
Assorted other info that may or may not help:

- The source has an `@RestrictTo(LIBRARY)` annotation (and an `@hide` javadoc)

- There is a [`ContentFrameLayout.java` stub](https://android.googlesource.com/platform/frameworks/support/+/7e82b99/v7/appcompat/src/android/support/v7/internal/widget/ContentFrameLayout.java) which has no `onAttachedToWindow` method.

**Comment by westnordost** [comment]
so it looks like proguard/R8 got silently more aggressive without me changing anything. Maybe the `proguard-android.txt`?

**Comment by smichel17** [comment]
You could try a release build with proguard/R8 disabled and see if that works… Anyway, I'm out of ideas and time I want to spend on this for now, I'll check back later / if anything else occurs to me.

**Comment by RubenKelevra** [comment]
@westnordost I did a perfetto system trace and it looks like android goes into OOM and that's why the app is killed 🤔

I'll poke a bit more around in the trace to see if I can get more out of it.

**Comment by westnordost** [comment]
Invalidate caches & restart, clean build and rebuild didn't change the outputted APK. It remains to be substantially smaller than the "real" one. Next step: Check what's in proguard-android.txt and see if it changed recently

**Comment by westnordost** [comment]
Findings so far:
- if proguard/R8 is switched off in the build.gradle, the problem is not reproducible. This confirms that it is a problem with proguard.
- built on a different machine, the problem is not reproducible at all

So it looks like proguard configuration on my main build machine is haywire somehow. Is there even such a thing as a proguard cache that I could clear?

**Comment by matkoniecz** [comment]
I once has a bizarre build problems and "`git push`, delete repo, clone repo in a different location" fixed it (sorry if that is not helpful)

**Comment by westnordost** [comment]
On my main build machine, I removed the complete ~/.m2 (local maven repos), ~/.gradle (local gradle stuff, except gradle.properties) and all build and .gradle folders in the project directory and build again. I think it works as normal now. I'm going to post a release candiate in a moment

**Comment by westnordost** [comment]
I am going to upload this version. I tested it on my device, it starts normally.
https://www.westnordost.de/misc/StreetComplete-v26.0-beta3.apk

**Comment by rouelibre1** [comment]
No more crash issues on launch for me.  Beta 3 solved it.

**Comment by kmpoppe** [comment]
Now everything works fine, thanks!

**Comment by Harvester57** [comment]
I confirm :)

**Comment by matkoniecz** [comment]
Sounds like a fixed bug :)
