### ISSUE TITLE
Quests won't open and app crashes

### ISSUE THREAD

**Issue by Norwi** [westnordost/StreetComplete#2286]
The app crashed twice.

> java.lang.NullPointerException: handler must not be null
at de.westnordost.streetcomplete.ktx.ViewKt$showTapHint$$inlined$postDelayed$1.run(Handler.kt:78)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7711)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

The first time was directly after updating and starting the app without any unusual bahaviour. The second time, I could not answer  'type of building' and 'lit' quests (the quests simply did not open on click). It seemed to be limited to a specific area only (maybe just the one quest cache?) and also to some quest types. After opening the app again (after the crash) everything was normal.

**How to Reproduce**
Not excactly sure - I just clicked on quests and browsed the map.

**Versions affected**
Android 10
StreetComplete v27.0-beta1

**Comment by RubenKelevra** [comment]
Had the app crash on me too, I've send a report via Google about the crash

**Comment by westnordost** [comment]
Also 
```
java.lang.NullPointerException: handler must not be null
at de.westnordost.streetcomplete.ktx.ViewKt.showTapHint(View.kt:43)
at de.westnordost.streetcomplete.ktx.ViewKt.showTapHint$default(View.kt:42)
at de.westnordost.streetcomplete.quests.lanes.LanesSelectPuzzle.setLaneCounts(LanesSelectPuzzle.kt:194)
at de.westnordost.streetcomplete.quests.lanes.AddLanesForm.updatePuzzleView(AddLanesForm.kt:201)
at de.westnordost.streetcomplete.quests.lanes.AddLanesForm.setStreetSideLayout(AddLanesForm.kt:197)
at de.westnordost.streetcomplete.quests.lanes.AddLanesForm.onViewCreated(AddLanesForm.kt:84)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2723)
at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
at de.westnordost.streetcomplete.MainActivity.onStart(MainActivity.java:180)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
at android.app.Activity.performStart(Activity.java:7157)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2980)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:280)
at android.app.ActivityThread.main(ActivityThread.java:6748)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by westnordost** [comment]
Happens when you exit the quest form before the "tap hint" animation finished (which starts delayed)
