### ISSUE TITLE
Error downloading quests

### ISSUE THREAD

**Issue by alejandroscf** [westnordost/StreetComplete#251]
When I try to download new quests in my neighborhood (Zaragoza, Spain[0]) I get an error and ask me to send you a bug report (and I've sent you several). The problem looks like it's related with the hosenumber qest and relations as the first stacktrace sais:
de.westnordost.osmapi.common.errors.XmlParserException: Error parsing XML at END_TAG </relation>@1329:14 in java.io.InputStreamReader@500b7c6

Hope this will help to solve the problem.
Also it will be nice if the download of other quest could continue after the error happen in order to at least get the other new quests.

[0]: http://www.openstreetmap.org/#map=17/41.62762/-0.87832

**Comment by alejandroscf** [comment]
Here the full stacktrace:
Device: google hammerhead, Android 6.0.1
de.westnordost.osmapi.common.errors.OsmApiReadResponseException: de.westnordost.osmapi.common.errors.XmlParserException: Error parsing XML at END_TAG </relation>@1329:14 in java.io.InputStreamReader@500b7c6
at de.westnordost.osmapi.OsmConnection.handleResponse(OsmConnection.java:318)
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:191)
at de.westnordost.streetcomplete.data.osm.download.OverpassMapDataDao.get(OverpassMapDataDao.java:60)
at de.westnordost.streetcomplete.data.osm.download.OverpassMapDataDao.getAndHandleQuota(OverpassMapDataDao.java:84)
at de.westnordost.streetcomplete.quests.housenumber.AddHousenumber.download(AddHousenumber.java:61)
at de.westnordost.streetcomplete.data.osm.download.OsmQuestDownload.download(OsmQuestDownload.java:71)
at de.westnordost.streetcomplete.data.download.QuestDownload.downloadQuestTypes(QuestDownload.java:204)
at de.westnordost.streetcomplete.data.download.QuestDownload.download(QuestDownload.java:122)
at de.westnordost.streetcomplete.data.download.QuestDownloadService$ServiceHandler.handleMessage(QuestDownloadService.java:184)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.os.HandlerThread.run(HandlerThread.java:61)


Caused by: de.westnordost.osmapi.common.errors.XmlParserException: Error parsing XML at END_TAG </relation>@1329:14 in java.io.InputStreamReader@500b7c6
at de.westnordost.osmapi.common.XmlParser.doParse(XmlParser.java:59)
at de.westnordost.streetcomplete.data.osm.download.OverpassMapDataParser.parse(OverpassMapDataParser.java:80)
at de.westnordost.streetcomplete.data.osm.download.OverpassMapDataParser.parse(OverpassMapDataParser.java:27)
at de.westnordost.osmapi.OsmConnection.handleResponse(OsmConnection.java:314)
... 11 more


Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.List de.westnordost.streetcomplete.data.osm.ElementGeometry.polygons' on a null object reference
at de.westnordost.streetcomplete.util.JTSConst.toGeometry(JTSConst.java:28)
at de.westnordost.streetcomplete.quests.housenumber.AddHousenumber$2.handle(AddHousenumber.java:65)
at de.westnordost.streetcomplete.data.osm.download.OverpassMapDataParser.onEndElement(OverpassMapDataParser.java:193)
at de.westnordost.osmapi.common.XmlParser.doParse(XmlParser.java:48)
... 14 more

**Comment by westnordost** [comment]
Yes it is already fixed for the next version.

(There are buildings with invalid geometry in the area you scanned.)

**Comment by gappleto97** [comment]
I'm seeing this sort of thing in Stanley Market, near Hong Kong. Can you verify its the same cause? The invalid buildings I mean?
