### ISSUE TITLE
Error downloading quests

### ISSUE THREAD

**Issue by NonnEmilia** [westnordost/StreetComplete#255]
When I try to search for new quests I receive these errors in the logcat:

```
05-21 10:01:23.369  9130 15196 I QuestDownload: Not downloading quest types because they are in local storage already: [AddRoadName, AddRoadSurface, NoteQuestType]
05-21 10:01:23.371  9130 15196 I QuestDownload: (10.634765625,44.68427737181224,10.6787109375,44.71551373202134) Starting
05-21 10:01:26.652  9130 15196 I QuestDownload: (10.634765625,44.68427737181224,10.6787109375,44.71551373202134) Finished
05-21 10:01:26.653  9130 15196 E QuestDownload: Unable to download quests
05-21 10:01:26.653  9130 15196 E QuestDownload: de.westnordost.osmapi.common.errors.OsmApiReadResponseException: de.westnordost.osmapi.common.errors.XmlParserException: Error parsing XML at END_TAG </relation>@1301:14 in java.io.InputStreamReader@342b2e2
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at de.westnordost.osmapi.OsmConnection.handleResponse(OsmConnection.java:318)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:191)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at de.westnordost.streetcomplete.data.osm.download.OverpassMapDataDao.get(OverpassMapDataDao.java:60)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at de.westnordost.streetcomplete.data.osm.download.OverpassMapDataDao.getAndHandleQuota(OverpassMapDataDao.java:84)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at de.westnordost.streetcomplete.quests.housenumber.AddHousenumber.download(AddHousenumber.java:61)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at de.westnordost.streetcomplete.data.osm.download.OsmQuestDownload.download(OsmQuestDownload.java:71)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at de.westnordost.streetcomplete.data.download.QuestDownload.downloadQuestTypes(QuestDownload.java:204)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at de.westnordost.streetcomplete.data.download.QuestDownload.download(QuestDownload.java:122)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at de.westnordost.streetcomplete.data.download.QuestDownloadService$ServiceHandler.handleMessage(QuestDownloadService.java:184)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at android.os.Looper.loop(Looper.java:234)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at android.os.HandlerThread.run(HandlerThread.java:61)
05-21 10:01:26.653  9130 15196 E QuestDownload: Caused by: de.westnordost.osmapi.common.errors.XmlParserException: Error parsing XML at END_TAG </relation>@1301:14 in java.io.InputStreamReader@342b2e2
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at de.westnordost.osmapi.common.XmlParser.doParse(XmlParser.java:59)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at de.westnordost.streetcomplete.data.osm.download.OverpassMapDataParser.parse(OverpassMapDataParser.java:80)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at de.westnordost.streetcomplete.data.osm.download.OverpassMapDataParser.parse(OverpassMapDataParser.java:27)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at de.westnordost.osmapi.OsmConnection.handleResponse(OsmConnection.java:314)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	... 11 more
05-21 10:01:26.653  9130 15196 E QuestDownload: Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.List de.westnordost.streetcomplete.data.osm.ElementGeometry.polygons' on a null object reference
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at de.westnordost.streetcomplete.util.JTSConst.toGeometry(JTSConst.java:28)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at de.westnordost.streetcomplete.quests.housenumber.AddHousenumber$2.handle(AddHousenumber.java:65)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at de.westnordost.streetcomplete.data.osm.download.OverpassMapDataParser.onEndElement(OverpassMapDataParser.java:193)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	at de.westnordost.osmapi.common.XmlParser.doParse(XmlParser.java:48)
05-21 10:01:26.653  9130 15196 E QuestDownload: 	... 14 more
```
StreetComplete 0.10 with Android 6.0.1

**Comment by matkoniecz** [comment]
Seems to be already reported, fixed but unreleased bug fixed in https://github.com/westnordost/StreetComplete/commit/b03379475dc7528801f8ed0f5e4209d8f66c76da

BTW, this bug makes for me impossible to download quests in city center - maybe releasing a new version would be a good idea?

**Comment by matkoniecz** [comment]
also, probably duplicate of #251

**Comment by NonnEmilia** [comment]
It's exactly the #251. I'm sorry for the duplicate.
