### ISSUE TITLE
NPE in QuestController

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#282]
Error report with stack trace that was sent to me.

Device: htc m7, Android 6.0.1
Thread: QuestControllerThread
Stack trace:
java.lang.NullPointerException: Attempt to invoke virtual method 'de.westnordost.osmapi.map.data.Element$Type de.westnordost.streetcomplete.data.osm.OsmQuest.getElementType()' on a null object reference
at de.westnordost.streetcomplete.data.QuestController$3.run(QuestController.java:160)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by westnordost** [comment]
> Scan for new quests for current location
> Takes a while
> Turn off the screen for ten minutes
> Turn the screen on
> Scanning has finished
> Look around my neighbourhood
> Tap a node (for opening hours)
> Programme force closes
> Runs fine afterward.

**Comment by westnordost** [comment]
This happens very often, 15 reports this week.

**Comment by westnordost** [comment]
Device: htc m7, Android 6.0.1
Thread: QuestControllerThread
Stack trace:
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Map de.westnordost.osmapi.map.data.Element.getTags()' on a null object reference
at de.westnordost.streetcomplete.data.QuestController$3.run(QuestController.java:161)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.os.HandlerThread.run(HandlerThread.java:61)
