### ISSUE TITLE
401 on closing changeset (ChangesetAutoCloserService)

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#283]
Error report with stack trace that was sent to me.

Device: Lenovo A2016a40, Android 6.0
Thread: IntentService[ChangesetAutoCloserService]
Stack trace:
de.westnordost.osmapi.common.errors.OsmAuthorizationException: Unauthorized (401) - Couldn't authenticate you
at de.westnordost.osmapi.OsmApiErrorFactory.createError(OsmApiErrorFactory.java:33)
at de.westnordost.osmapi.OsmConnection.handleResponseCode(OsmConnection.java:343)
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:189)
at de.westnordost.osmapi.OsmConnection.makeAuthenticatedRequest(OsmConnection.java:161)
at de.westnordost.osmapi.map.MapDataDao.closeChangeset(MapDataDao.java:170)
at de.westnordost.streetcomplete.data.osm.upload.OsmQuestChangesUpload.closeOpenChangesets(OsmQuestChangesUpload.java:114)
at de.westnordost.streetcomplete.data.osm.upload.ChangesetAutoCloserService.onHandleIntent(ChangesetAutoCloserService.java:26)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:207)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by westnordost** [comment]
This happens quite often. 5 reports this week.
