### ISSUE TITLE
LOST exception

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#284]
Error report that was sent to me.

Device: samsung klte, Android 7.1.2
Thread: main
Stack trace:
java.lang.IllegalArgumentException: Service not registered: com.mapzen.android.lost.internal.FusedLocationProviderApiImpl@f90572a
	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1289)
	at android.app.ContextImpl.unbindService(ContextImpl.java:1483)
	at android.content.ContextWrapper.unbindService(ContextWrapper.java:648)
	at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.onDisconnect(FusedLocationProviderApiImpl.java:55)
	at com.mapzen.android.lost.internal.FusedLocationServiceConnectionManager.disconnect(FusedLocationServiceConnectionManager.java:70)
	at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.disconnect(FusedLocationProviderApiImpl.java:92)
	at com.mapzen.android.lost.internal.LostApiClientImpl.disconnect(LostApiClientImpl.java:60)
	at de.westnordost.streetcomplete.location.SingleLocationRequest$1.run(SingleLocationRequest.java:52)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by westnordost** [comment]
Might be fixed by new lost version.
