### ISSUE TITLE
IllegalArgumentException on solving quest twice(?)

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#289]
This exception is not new. I haven't been able to find the source. It seems to happen when quests mysteriously reappear after solving them.

java.lang.IllegalArgumentException: 
  at de.westnordost.streetcomplete.data.osm.changes.StringMapChangesBuilder.add(StringMapChangesBuilder.java:36)
  at de.westnordost.streetcomplete.quests.sport.AddSport.applyAnswerTo(AddSport.java:46)
  at de.westnordost.streetcomplete.data.QuestController$3.run(QuestController.java:162)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:135)
  at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by matkoniecz** [comment]
> it seems to happen when quests mysteriously reappear after solving them.

Maybe it us #215?

**Comment by westnordost** [comment]
Thats a good hint, will look into that.
