### ISSUE TITLE
Crash with sidewalk overlay

### ISSUE THREAD

**Issue by joshinils** [westnordost/StreetComplete#4169]
**How to Reproduce**

With the sidewalk overlay on, tap on way https://www.openstreetmap.org/way/16903057

**Versions affected**

45.0-beta1

**Comment by westnordost** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.westnordost.streetcomplete.debug, PID: 24826
    android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:509)
        at android.content.res.Resources.getString(Resources.java:602)
        at de.westnordost.streetcomplete.view.TextKt.setText(Text.kt:23)
        at de.westnordost.streetcomplete.view.StreetSideSelectPuzzle.setLeftSideText(StreetSideSelectPuzzle.kt:166)
        at de.westnordost.streetcomplete.view.controller.StreetSideSelectWithLastAnswerButtonViewController.setPuzzleSide(StreetSideSelectWithLastAnswerButtonViewController.kt:136)
        at de.westnordost.streetcomplete.overlays.sidewalk.SidewalkOverlayForm.initStateFromTags(SidewalkOverlayForm.kt:36)
        at de.westnordost.streetcomplete.overlays.sidewalk.SidewalkOverlayForm.onViewCreated(SidewalkOverlayForm.kt:29)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

**Comment by matkoniecz** [comment]
`sidewalk:right = separate` without `sidewalk:left = separate`?

**Comment by joshinils** [comment]
> `sidewalk:right = separate` without `sidewalk:left = separate`?

You're saying I should tag it with `sidewalk:left=no`? the middle island is too big to count as a sidewalk, there are trees and the path that exists is in the middle and there are benches

**Comment by matkoniecz** [comment]
Not sure, but either way SC should not crash on encountering such case. I edited my comment to make it more clear
