### ISSUE TITLE
application crash when send a report to specify route name

### ISSUE THREAD

**Issue by madeindjs** [westnordost/StreetComplete#417]
I found a bug when I want to specify road type. Here how to reproduce :

- Select a road with no type
- Select "it's not road" option
- Select "specify" option and enter a text (content doesn't matter) 
- Send the report and application will crash

Device: Sony D5803, Android 6.0.1
Thread: main

Stack trace:

~~~
android.content.res.Resources$NotFoundException: String resource ID #0x7f090121
	at android.content.res.Resources.getText(Resources.java:319)
	at android.content.res.Resources.getString(Resources.java:407)
	at de.westnordost.streetcomplete.quests.LeaveNoteDialog.onClickOk(LeaveNoteDialog.java:98)
	at de.westnordost.streetcomplete.quests.LeaveNoteDialog.access$100(LeaveNoteDialog.java:16)
	at de.westnordost.streetcomplete.quests.LeaveNoteDialog$2.onClick(LeaveNoteDialog.java:54)
	at android.view.View.performClick(View.java:5280)
	at android.view.View$PerformClick.run(View.java:21239)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:234)
	at android.app.ActivityThread.main(ActivityThread.java:5526)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
~~~

**Comment by westnordost** [comment]
Please update to the newest version, this is fixed already.
