### ISSUE TITLE
Weird grey block for bike lanes quest

### ISSUE THREAD

**Issue by Phyks** [westnordost/StreetComplete#713]
Hi,

In the "is there a bike lane" quest, I am having a grey block, not sure if this is expected or not. Here is a screenshot:

![screenshot_2017-11-30-15-00-19](https://user-images.githubusercontent.com/3856586/33434403-7bac05c0-d5df-11e7-9cea-5ee64c183bb5.png)

When clicking on it, I have the correct popover opening to pick a type of bike route. When I click on a certain type, the popover disappear but the grey block is not updated.

I think the grey block should be an illustration of the type of bike route selected. Otherwise, there is no way to confirm the correct bike route type as been chosen :)

I am using Android AOSP 4.2.2 (on a Fairphone FP1) and StreetComplete 3.2 from F-Droid. Let me know if I can help debug it further in any ways.

Thanks for all the work you are putting on this wonderful app!

EDIT: Upon selecting a bike route type and clicking "ok", I get an error message "Please select a bike route type for both ways", but I only have one clickable item (the grey block).

EDIT 2: On another way, when clicking the bike route quest, I got a crash of StreetComplete.

**Comment by westnordost** [comment]
Oh no, the fairphone with the stuck 4.2.2.

Yeah, there should be an illustration of a road with two sides, each of them is clickable.

I guess this is an Android 4.2.2 problem,...  Perhaps there is a workaround for that.

**Comment by Phyks** [comment]
Erf, yes, I'm stuck with 4.2.2 :( It would be awesome to have a fix for this, as I guess I'm not the only one stuck with 4.2.2. But I'm not sure whether it is worth investing too much time debugging it…

I also have an issue with "is there a tactile signal for this pedestrian crossing?" quest, clicking the icon that matches the tactile signal does not select it. So far, that's the only particular issues I found with new quests :)

**Comment by Phyks** [comment]
Not sure if it can help to fix the grey block issue, but for the crashing issue here is the `adb logcat` I managed to get:

```
W/dalvikvm(13349): threadid=1: thread exiting with uncaught exception (group=0x4189d9a8)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [release] fps:63.43, dur:1008.97, max:16.15, min:15.51
I/SurfaceTextureClient(13349): [STC::queueBuffer] (this:0x6243f758) fps:63.38, dur:1009.71, max:23.28, min:8.57
E/AndroidRuntime(13349): FATAL EXCEPTION: main
E/AndroidRuntime(13349): java.lang.NullPointerException
E/AndroidRuntime(13349): 	at de.westnordost.streetcomplete.quests.bikeway.AddCyclewayForm.getWayOrientationAtCenterLineInDegrees(AddCyclewayForm.java:143)
E/AndroidRuntime(13349): 	at de.westnordost.streetcomplete.quests.bikeway.AddCyclewayForm.onCreateView(AddCyclewayForm.java:63)
E/AndroidRuntime(13349): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
E/AndroidRuntime(13349): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
E/AndroidRuntime(13349): 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
E/AndroidRuntime(13349): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
E/AndroidRuntime(13349): 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
E/AndroidRuntime(13349): 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
E/AndroidRuntime(13349): 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
E/AndroidRuntime(13349): 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
E/AndroidRuntime(13349): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
E/AndroidRuntime(13349): 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
E/AndroidRuntime(13349): 	at android.os.Handler.handleCallback(Handler.java:725)
E/AndroidRuntime(13349): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(13349): 	at android.os.Looper.loop(Looper.java:153)
E/AndroidRuntime(13349): 	at android.app.ActivityThread.main(ActivityThread.java:5299)
E/AndroidRuntime(13349): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(13349): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(13349): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
E/AndroidRuntime(13349): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
E/AndroidRuntime(13349): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime(13349): 	at dalvik.system.NativeStart.main(Native Method)
I/BufferQueue(  534): [StatusBar](this:0x41d9da80,api:1) [queue] fps:5.93, dur:1011.08, max:333.07, min:28.14
W/ActivityManager(  569):   Force finishing activity de.westnordost.streetcomplete/.MainActivity
I/PowerManagerService(  569): setBrightness mButtonLight 0.
W/AES     (  569): Exception Log handling...
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] fps:63.46, dur:1008.49, max:23.59, min:11.49
E/AppErrorDialog(  569): Failed to get ILowStorageHandle instance
I/SurfaceFlinger(  534): [SurfaceFlinger] fps:63.426914,dur:1009.04,max:29.52,min:6.67
I/SurfaceFlinger(  534): EventThread Client Pid (569) created
I/WindowManager(  569): Gaining focus: Window{4224def8 u0 Application Error: de.westnordost.streetcomplete}
I/BufferQueue(  534): [unnamed-534-566](this:0x41fb7b58,api:0) BufferQueue
I/BufferQueue(  534): [unnamed-534-566](this:0x41fb7b58,api:0) consumerConnect
I/BufferQueue(  534): [unnamed-534-566](this:0x41fb7b58,api:0) setConsumerName: unnamed-534-566
I/SurfaceTexture(  534): [unnamed-534-566](this:0x41daa220,api:0) SurfaceTexture
I/BufferQueue(  534): [unnamed-534-566](this:0x41fb7b58,api:0) setSynchronousMode: enabled=1
I/BufferQueue(  534): [unnamed-534-566](this:0x41fb7b58,api:0) setDefaultBufferSize: w=1, h=1
I/BufferQueue(  534): [Application Error: de.westnordost.streetcomplete](this:0x41fb7b58,api:0) setConsumerName: Application Error: de.westnordost.streetcomplete
I/BufferQueue(  534): [Application Error: de.westnordost.streetcomplete](this:0x41fb7b58,api:0) setDefaultBufferSize: w=480, h=190
I/BufferQueue(  534): [Application Error: de.westnordost.streetcomplete](this:0x41fb7b58,api:0) connect: api=2
I/BufferQueue(  534): [Application Error: de.westnordost.streetcomplete](this:0x41fb7b58,api:2) setSynchronousMode: enabled=1
I/BufferQueue(  534): [Application Error: de.westnordost.streetcomplete](this:0x41fb7b58,api:2) new GraphicBuffer needed
I/GraphicBuffer(  534): allocate buffer (w:480 h:190 f:1) err(0)
I/BufferQueue(  534):     [NEW] gb=0x41dd1bc8, handle=0x41e36e38, w=480, h=190, s=480, fmt=1
I/SurfaceTexture(  534): [Application Error: de.westnordost.streetcomplete](this:0x41daa220,api:2) [void* android::SurfaceTexture::createImage(EGLDisplay, const android::sp<android::GraphicBuffer>&)]
I/SurfaceTextureClient(  534): [STC::queueBuffer] (this:0x419538b8) fps:0.18, dur:16543.41, max:16512.01, min:15.39
I/SurfaceTextureClient(  534): [STC::queueBuffer] this:0x419538b8, api:1, last queue time elapsed:16512.01
I/BufferQueue(  534): [FramebufferSurface](this:0x41956008,api:1) [release] fps:0.18, dur:16543.41, max:16512.07, min:15.38
I/BufferQueue(  534): [FramebufferSurface](this:0x41956008,api:1) [queue] fps:0.18, dur:16543.41, max:16512.08, min:15.39
I/WifiStateMachine(  569): fetchRssiAndLinkSpeedNative, newRssi:-57, newLinkSpeed:65
I/SurfaceTextureClient(13349): [STC::queueBuffer] (this:0x63ac3308) fps:60.35, dur:1010.76, max:33.76, min:4.07
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] fps:60.34, dur:1010.88, max:34.02, min:4.19
I/System.out(  569): setUpTheReceiver onReceive
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [release] fps:60.48, dur:1008.64, max:31.68, min:0.76
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [StatusBar](this:0x41d9da80,api:1) [release] fps:5.60, dur:1071.48, max:331.48, min:31.35
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
E/IMGSRV  (13349): :0: skip glDrawElements (indices=1(0x0), bindBuffer=1)
E/IMGSRV  (13349): :0: skip glDrawElements (indices=1(0x0), bindBuffer=1)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/SurfaceTextureClient(  668): [STC::queueBuffer] (this:0x5d0c40d8) fps:5.95, dur:1008.86, max:333.13, min:17.56
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
W/ActivityManager(  569): Activity pause timeout for ActivityRecord{41f697c8 u0 de.westnordost.streetcomplete/.MainActivity}
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
E/IMGSRV  (13349): :0: skip glDrawElements (indices=1(0x0), bindBuffer=1)
E/IMGSRV  (13349): :0: skip glDrawElements (indices=1(0x0), bindBuffer=1)
E/IMGSRV  (13349): :0: skip glDrawElements (indices=1(0x0), bindBuffer=1)
E/IMGSRV  (13349): :0: skip glDrawElements (indices=1(0x0), bindBuffer=1)
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dc4008,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [SurfaceView](this:0x41dae030,api:1) [queue] queued:2 (lag)
I/BufferQueue(  534): [unnamed-534-567](this:0x41e11480,api:0) BufferQueue
I/BufferQueue(  534): [unnamed-534-567](this:0x41e11480,api:0) consumerConnect
I/BufferQueue(  534): [unnamed-534-567](this:0x41e11480,api:0) setConsumerName: unnamed-534-567
I/SurfaceTexture(  534): [unnamed-534-567](this:0x41dd13b8,api:0) SurfaceTexture
I/BufferQueue(  534): [unnamed-534-567](this:0x41e11480,api:0) setSynchronousMode: enabled=1
I/BufferQueue(  534): [unnamed-534-567](this:0x41e11480,api:0) setDefaultBufferSize: w=540, h=960
```

**Comment by westnordost** [comment]
The crash will be easy to fix. For the surface-stuff, I will need to install a 4.2.2 emulator and try out some stuff.

**Comment by Phyks** [comment]
That's a good news for the crash!

Not sure how difficult it might be to fix it completely for Android 4.2.2. If this is too long / difficult compared to the userbase in 4.2.2, it might be worth simply deactivating the quest on 4.2.2?

I still have my Fairphone under 4.2.2 at hand, I can try stuff if it can help. :)

**Comment by westnordost** [comment]
Hmm, I cannot at all start StreetComplete in an Android 4.2.2 emulator. I get
```A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 4024 (Thread-127)```
and that was it.

I guess I must get my hands on a fairphone 1 or something to test. A friend of mine has one, perhaps I can borrow it (she wants to buy a new smartphone anyway). In the meantime, I will disable the quest for Android 4.2.2.

**Comment by westnordost** [comment]
StreetComplete has only 31 users (0.5%) that still use Android 4.2.

**Comment by Phyks** [comment]
Thanks!
